function choosefont(){
  let titlefch=myRandom(0,1);
  let bodyfch=myRandom(0,1);
  if (bodyfch<1)bfont=Arapey;
  if (bodyfch<0.92)bfont=Oxford;
  if (bodyfch<0.88)bfont=Bluegrass;
  if (bodyfch<0.84)bfont=Playfair;
  if (bodyfch<0.80)bfont=Droid;
  if (bodyfch<0.76)bfont=Quicksand;
  if (bodyfch<0.72)bfont=TattyB;
  if (bodyfch<0.68)bfont=Tatty;
  if (bodyfch<0.64)bfont=Orgreave;
  if (bodyfch<0.60)bfont=Vollkorn;
  if (bodyfch<0.56)bfont=DroidI;
  if (bodyfch<0.52)bfont=Earth;
  if (bodyfch<0.48)bfont=NegarHI;
  if (bodyfch<0.44)bfont=Swansea;
  if (bodyfch<0.40)bfont=Simvoni;
  if (bodyfch<0.36)bfont=Sanlulus;
  if (bodyfch<0.32)bfont=Regencie;
  if (bodyfch<0.28)bfont=Quinngothic;
  if (bodyfch<0.24)bfont=Quango;
  if (bodyfch<0.20)bfont=Muli;
  if (bodyfch<0.16)bfont=Mangabey;
  if (bodyfch<0.12)bfont=Jufatti;
  if (bodyfch<0.08)bfont=Elmessiri;
  if (titlefch<1){tfont=Aelia;hfont=Arapey;bfont=Arapey;scalar=0.8}
  if (titlefch<0.975){tfont=Argentile;hfont=TattyB;bfont=TattyB;scalar=1.1}
  if (titlefch<0.95){tfont=ArgentileD;hfont=Tatty;bfont=Tatty;scalar=1.1}
  if (titlefch<0.925){tfont=Bluegrass;hfont=Bluegrass;scalar=0.9}
  if (titlefch<0.9){tfont=Droid;hfont=Droid;scalar=0.75}
  if (titlefch<0.875){tfont=DroidB;hfont=DroidBI;scalar=0.75}
  if (titlefch<0.85){tfont=DroidBI;hfont=DroidB;scalar=0.75}
  if (titlefch<0.825){tfont=Rondal;hfont=Rondal;scalar=1}
  if (titlefch<0.8){tfont=RondalB;hfont=RondalSB;scalar=1}
  if (titlefch<0.775){tfont=RondalSB;hfont=Rondal;scalar=1}
  if (titlefch<0.75){tfont=Earth;hfont=Earth;bfont=Earth;scalar=0.8}
  if (titlefch<0.725){tfont=Foglihtenno;hfont=Quicksand;bfont=Quicksand;scalar=0.9}
  if (titlefch<0.7){tfont=Playfair;hfont=Playfair;scalar=1}
  if (titlefch<0.675){tfont=Tatty;hfont=Tatty;bfont=Tatty;scalar=1}
  if (titlefch<0.65){tfont=TattyB;hfont=Tatty;bfont=Tatty;scalar=1}
  if (titlefch<0.625){tfont=Orgreave;hfont=Orgreave;scalar=1}
  if (titlefch<0.6){tfont=Oxford;hfont=Oxford;scalar=1}
  if (titlefch<0.575){tfont=Raffles;hfont=Raffles;scalar=0.7}
  if (titlefch<0.55){tfont=RafflesB;hfont=RafflesB;scalar=0.7}
  if (titlefch<0.525){tfont=Raffles;hfont=Raffles;scalar=0.7}
  if (titlefch<0.5){tfont=RafflesO;hfont=Quicksand;bfont=Quicksand;scalar=1}
  if (titlefch<0.475){tfont=Vollkorn;hfont=Vollkorn;scalar=1}
  if (titlefch<0.45){tfont=Stompb;hfont=Stompb;bfont=DroidB;scalar=0.9}
  if (titlefch<0.425){tfont=RogueB;hfont=RogueB;bfont=Playfair;scalar=0.8}
  if (titlefch<0.4){tfont=Aurebesh;hfont=Stompb;}
  if (titlefch<0.35){tfont=Bebas;hfont=Bebas;}
  if (titlefch<0.325){tfont=Bootle;hfont=Bootle;}
  if (titlefch<0.3){tfont=Buyan;hfont=Buyan;}
  if (titlefch<0.275){tfont=Elmessiri;hfont=Elmessiri;}
  if (titlefch<0.25){tfont=LicensePlate;hfont=LicensePlate;}
  if (titlefch<0.225){tfont=Mangabey;hfont=Mangabey;}
  if (titlefch<0.175){tfont=Nugie;hfont=Nugie;scalar=0.8}
  if (titlefch<0.15){tfont=Pasti;hfont=Pasti;}
  if (titlefch<0.1){tfont=Quango;hfont=Quango;}
  if (titlefch<0.075){tfont=Quinngothic;hfont=Quinngothic;}
  if (titlefch<0.05){tfont=Satella;hfont=Satella;}
  if (titlefch<0.025){tfont=Understock;hfont=Understock;}
}