var count = 0;
var sm = 2.4;
var sm2 = 0.4;
var zf = 0.002;
var zf2 = 0.002;
var fr = 0;
var wave1 = [];
var wave2 = [];
var fbi = [];
var fbj = [];
function pgfabric1(f1x, f1y, f1w, f1h) {
  sm = 2.4;
  sm2 = 0.4;
  zf = 0.002;
  zf2 = 0.002;
  fr = 0;
  noiseSeed(myRandom(0, 1000));
  pg.noStroke();
  pg.fill(255);
  let rows = f1h + f1y;
  let columns = f1w + f1x;
  for (let j = f1y; j < rows; j += g[16]) {
    fc = 0;
    wave1[j] = [];
    wave2[j] = [];
    for (let a = 0; a < PI * 2; a += PI / 640) {
      let xf = pg.map(cos(a), -1, 1, 0, sm);
      let yf = pg.map(sin(a), -1, 1, 0, sm);
      let xf2 = pg.map(cos(a), -1, 1, 0, sm2);
      let yf2 = pg.map(sin(a), -1, 1, 0, sm2);
      r = pg.map(noise(xf, yf, zf), 0, 1, g[0], g[210]);
      r2 = pg.map(noise(yf2, xf2, zf2), 0, 1, g[0], g[100]);
      wave2[j].push(r2);
      wave1[j].push(r);
      sm += 0.000018;
      sm2 += 0.000016;
    }
    zf += 0.00001;
    for (let i = f1x; i < columns; i += g[16]) {
      if (fr < 1) pgfraytop(i + wave2[j][count], j + wave1[j][count]);
      if (fc < 1) pgfrayleft(i + wave2[j][count], j + wave1[j][count]);
      pgweave(i + wave2[j][count], j + wave1[j][count]);
      if (j > f1y + f1h - g[16])
        pgfraybottom(i + wave2[j][count], j + wave1[j][count] + g[16]);
      fc = 1;
      count += 1;
    }
    pgfrayright(f1x + f1w + wave2[j][count], j + wave1[j][count]);
    fr = 1;
    count = 0;
  }
}
function pgweave(i, j) {
  let x = i;
  let y = j;
  let tr = myRandom(0, 1);
  pg.fill(features.f1sh1a); //square shadows
  if (tr < 0.7) pg.fill(features.f1sh2a);
  if (tr < 0.4) pg.fill(features.f1sh3a);
  pg.rect(x, y, g[4], g[4]);
  pg.rect(x + g[8], y, g[4], g[4]);
  pg.rect(x + g[8], y + g[8], g[4], g[12]);
  pg.rect(x, y + g[8], g[4], g[12]);
  pg.fill(features.f1sh1); //shadows on vertical
  if (tr < 0.7) pg.fill(features.f1sh2);
  if (tr < 0.4) pg.fill(features.f1sh3);
  pg.rect(x + g[4], y, g[4], g[12]);
  pg.rect(x + g[12], y + g[0], g[4], g[4]);
  pg.rect(x + g[12], y + g[8], g[4], g[16]);
  pg.rect(x + g[4], y + g[16], g[4], g[8]);
  pg.fill(features.f1sh1); //shadows on horizontal
  if (tr < 0.7) pg.fill(features.f1sh2);
  if (tr < 0.4) pg.fill(features.f1sh3);
  pg.rect(x + g[0], y + g[4], g[4], g[4]);
  pg.rect(x + g[8], y + g[4], g[8], g[4]);
  pg.rect(x + g[0], y + g[12], g[12], g[4]);
  pg.fill(features.f1h); //highlights on vertical
  pg.arc(x + g[4], y + g[4], g[6], g[6], -PI / 2, 0);
  pg.rect(x + g[12], y + g[0], g[3], g[4]);
  pg.arc(x + g[12], y + g[12], g[6], g[6], -PI / 2, 0);
  pg.rect(x + g[4], y + g[4], g[3], g[8]);
  pg.rect(x + g[12], y + g[12], g[3], g[12]);
  pg.fill(features.f1h); //highlights on horizontal
  pg.arc(x + g[0], y + g[4], g[6], g[6], 0, PI / 2);
  pg.arc(x + g[12], y + g[4], g[6], g[6], PI / 2, PI);
  pg.arc(x + g[4], y + g[12], g[6], g[6], PI / 2, PI);
  pg.arc(x + g[8], y + g[12], g[6], g[6], 0, PI / 2);
  pg.rect(x + g[12], y + g[4], g[4], g[3]);
  pg.rect(x + g[4], y + g[12], g[4], g[3]);
  tr = myRandom(0, 1);
  pg.stroke(features.cornshadowa);
  li=myRandom(g[0],g[4]);lj=myRandom(g[8],g[10]);
  pg.strokeWeight(g[1]);  
  pg.line(i+g[4],j+g[0]+li,i+g[8],j+g[0]+lj);
  li=myRandom(g[0],g[4]);lj=myRandom(g[8],g[10]);
  pg.line(i+g[0]+li,j+g[16],i+g[0]+lj,j+g[12]);
  pg.line(i+g[0],j+g[5],i+g[2],j+g[4]);
  pg.line(i+g[10],j+g[8],i+g[16],j+g[5]);
  pg.line(i+g[15],j+g[0],i+g[16],j+g[2]);
  pg.line(i+g[12],j+g[10],i+g[15],j+g[16]);
  pg.noStroke();
}
function pgfrayleft(i, j) {
  pg.fill(features.cornshadow);
  pg.noStroke();
  let x = i;
  let y = j;
  pg.beginShape();
  pg.vertex(x, y + g[7]);
  pg.curveVertex(x, y + g[7]);
  pg.curveVertex(x - myRandom(g[10], g[20]), y + myRandom(g[6], g[8]));
  pg.curveVertex(x - myRandom(g[25], g[35]), y + myRandom(g[6], g[8]));
  pg.vertex(x - myRandom(g[30], g[45]), y + myRandom(g[3], g[11]));
  pg.curveVertex(x - myRandom(g[25], g[35]), y + myRandom(g[10], g[12]));
  pg.curveVertex(x - myRandom(g[10], g[20]), y + myRandom(g[10], g[12]));
  pg.vertex(x, y + g[11]);
  pg.endShape(CLOSE);
  pg.beginShape();
  pg.vertex(x, y + g[15]);
  pg.curveVertex(x, y + g[15]);
  pg.curveVertex(x - myRandom(g[10], g[20]), y + myRandom(g[14], g[16]));
  pg.curveVertex(x - myRandom(g[25], g[35]), y + myRandom(g[14], g[16]));
  pg.vertex(x - myRandom(g[30], g[45]), y + myRandom(g[11], g[19]));
  pg.curveVertex(x - myRandom(g[25], g[35]), y + myRandom(g[18], g[20]));
  pg.curveVertex(x - myRandom(g[10], g[20]), y + myRandom(g[18], g[20]));
  pg.vertex(x, y + g[19]);
  pg.endShape(CLOSE);
  pg.fill(features.f1h);
  pg.noStroke();
  pg.beginShape();
  pg.vertex(x, y + g[4]);
  pg.curveVertex(x, y + g[4]);
  pg.curveVertex(x - myRandom(g[10], g[15]), y + myRandom(g[3], g[5]));
  pg.curveVertex(x - myRandom(g[25], g[30]), y + myRandom(g[3], g[5]));
  pg.vertex(x - myRandom(g[30], g[40]), y + myRandom(g[0], g[8]));
  pg.curveVertex(x - myRandom(g[25], g[30]), y + myRandom(g[7], g[9]));
  pg.curveVertex(x - myRandom(g[10], g[15]), y + myRandom(g[7], g[9]));
  pg.vertex(x, y + g[8]);
  pg.endShape(CLOSE);
  pg.beginShape();
  pg.vertex(x, y + g[12]);
  pg.curveVertex(x, y + g[12]);
  pg.curveVertex(x - myRandom(g[10], g[15]), y + myRandom(g[11], g[13]));
  pg.curveVertex(x - myRandom(g[25], g[30]), y + myRandom(g[11], g[13]));
  pg.vertex(x - myRandom(g[30], g[40]), y + myRandom(g[8], g[16]));
  pg.curveVertex(x - myRandom(g[25], g[30]), y + myRandom(g[15], g[17]));
  pg.curveVertex(x - myRandom(g[10], g[15]), y + myRandom(g[15], g[17]));
  pg.vertex(x, y + g[16]);
  pg.endShape(CLOSE);
  pg.stroke(features.cornshadowab);
  pg.strokeWeight(g[1]);  
  pg.line(x,y+g[4],x-myRandom(g[8],g[16]),y+g[8]);
  pg.line(x-g[10],y+g[4],x-myRandom(g[18],g[30]),y+g[8]);  
  pg.line(x,y+g[12],x-myRandom(g[8],g[16]),y+g[16]);
  pg.line(x-g[10],y+g[12],x-myRandom(g[18],g[30]),y+g[16]);
  pg.noStroke();
}
function pgfrayright(i, j) {
  let x = i;
  let y = j;
  pg.fill(features.cornshadow);
  pg.noStroke();
  pg.beginShape();
  pg.vertex(x, y + g[4]);
  pg.curveVertex(x, y + g[4]);
  pg.curveVertex(x + myRandom(g[10], g[20]), y + myRandom(g[6], g[8]));
  pg.curveVertex(x + myRandom(g[25], g[35]), y + myRandom(g[6], g[8]));
  pg.vertex(x + myRandom(g[30], g[45]), y + myRandom(g[3], g[11]));
  pg.curveVertex(x + myRandom(g[25], g[35]), y + myRandom(g[10], g[12]));
  pg.curveVertex(x + myRandom(g[10], g[20]), y + myRandom(g[10], g[12]));
  pg.curveVertex(x, y + g[11]);
  pg.vertex(x, y + g[8]);
  pg.endShape(CLOSE);
  pg.beginShape();
  pg.vertex(x, y + g[15]);
  pg.curveVertex(x, y + g[15]);
  pg.curveVertex(x + myRandom(g[10], g[20]), y + myRandom(g[14], g[16]));
  pg.curveVertex(x + myRandom(g[25], g[35]), y + myRandom(g[14], g[16]));
  pg.vertex(x + myRandom(g[30], g[45]), y + myRandom(g[11], g[19]));
  pg.curveVertex(x + myRandom(g[25], g[35]), y + myRandom(g[18], g[20]));
  pg.curveVertex(x + myRandom(g[10], g[20]), y + myRandom(g[18], g[20]));
  pg.curveVertex(x, y + g[16]);
  pg.vertex(x, y + g[16]);
  pg.endShape(CLOSE);
  pg.fill(features.f1h);
  pg.beginShape();
  pg.vertex(x, y + g[4]);
  pg.curveVertex(x, y + g[4]);
  pg.curveVertex(x + myRandom(g[10], g[15]), y + myRandom(g[3], g[5]));
  pg.curveVertex(x + myRandom(g[25], g[30]), y + myRandom(g[3], g[5]));
  pg.vertex(x + myRandom(g[30], g[40]), y + myRandom(g[0], g[8]));
  pg.curveVertex(x + myRandom(g[25], g[30]), y + myRandom(g[7], g[9]));
  pg.curveVertex(x + myRandom(g[10], g[15]), y + myRandom(g[7], g[9]));
  pg.curveVertex(x, y + g[8]);
  pg.vertex(x, y + g[8]);
  pg.endShape(CLOSE);
  pg.beginShape();
  pg.vertex(x, y + g[12]);
  pg.curveVertex(x, y + g[12]);
  pg.curveVertex(x + myRandom(g[10], g[15]), y + myRandom(g[11], g[13]));
  pg.curveVertex(x + myRandom(g[25], g[30]), y + myRandom(g[11], g[13]));
  pg.vertex(x + myRandom(g[30], g[40]), y + myRandom(g[8], g[16]));
  pg.curveVertex(x + myRandom(g[25], g[30]), y + myRandom(g[15], g[17]));
  pg.curveVertex(x + myRandom(g[10], g[15]), y + myRandom(g[15], g[17]));
  pg.curveVertex(x, y + g[16]);
  pg.vertex(x, y + g[16]);
  pg.endShape(CLOSE);
  pg.stroke(features.cornshadowab);
  pg.strokeWeight(g[1]);  
  pg.line(x,y+g[4],x+myRandom(g[8],g[16]),y+g[8]);
  pg.line(x+g[10],y+g[4],x+myRandom(g[18],g[30]),y+g[8]);  
  pg.line(x,y+g[12],x+myRandom(g[8],g[16]),y+g[16]);
  pg.line(x+g[10],y+g[12],x+myRandom(g[18],g[30]),y+g[16]);
  pg.noStroke();
}
function pgfraytop(i, j) {
  let x = i;
  let y = j;
  pg.fill(features.cornshadow);
  pg.noStroke();
  pg.beginShape();
  pg.vertex(x + g[6], y);
  pg.curveVertex(x + g[6], y);
  pg.curveVertex(x + myRandom(g[3], g[7]), y - myRandom(g[10], g[20]));
  pg.curveVertex(x + myRandom(g[3], g[7]), y - myRandom(g[25], g[35]));
  pg.vertex(x + myRandom(g[0], g[10]), y - myRandom(g[30], g[45]));
  pg.curveVertex(x + myRandom(g[7], g[11]), y - myRandom(g[25], g[35]));
  pg.curveVertex(x + myRandom(g[7], g[11]), y - myRandom(g[10], g[20]));
  pg.vertex(x + g[10], y);
  pg.endShape(CLOSE);
  pg.beginShape();
  pg.vertex(x + g[14], y);
  pg.curveVertex(x + g[14], y);
  pg.curveVertex(x + myRandom(g[11], g[15]), y - myRandom(g[10], g[20]));
  pg.curveVertex(x + myRandom(g[11], g[15]), y - myRandom(g[25], g[35]));
  pg.vertex(x + myRandom(g[8], g[18]), y - myRandom(g[30], g[45]));
  pg.curveVertex(x + myRandom(g[15], g[19]), y - myRandom(g[25], g[35]));
  pg.curveVertex(x + myRandom(g[15], g[19]), y - myRandom(g[10], g[20]));
  pg.vertex(x + g[18], y);
  pg.endShape(CLOSE);
  pg.fill(features.f1h);
  pg.beginShape();
  pg.vertex(x + g[4], y);
  pg.curveVertex(x + g[4], y);
  pg.curveVertex(x + myRandom(g[3], g[5]), y - myRandom(g[10], g[15]));
  pg.curveVertex(x + myRandom(g[3], g[5]), y - myRandom(g[25], g[30]));
  pg.vertex(x + myRandom(g[0], g[8]), y - myRandom(g[30], g[40]));
  pg.curveVertex(x + myRandom(g[7], g[9]), y - myRandom(g[25], g[30]));
  pg.curveVertex(x + myRandom(g[7], g[9]), y - myRandom(g[10], g[15]));
  pg.vertex(x + g[8], y);
  pg.endShape(CLOSE);
  pg.beginShape();
  pg.vertex(x + g[12], y);
  pg.curveVertex(x + g[12], y);
  pg.curveVertex(x + myRandom(g[11], g[13]), y - myRandom(g[10], g[15]));
  pg.curveVertex(x + myRandom(g[11], g[13]), y - myRandom(g[25], g[30]));
  pg.vertex(x + myRandom(g[8], g[16]), y - myRandom(g[30], g[40]));
  pg.curveVertex(x + myRandom(g[15], g[17]), y - myRandom(g[25], g[30]));
  pg.curveVertex(x + myRandom(g[15], g[17]), y - myRandom(g[10], g[15]));
  pg.vertex(x + g[16], y);
  pg.endShape(CLOSE);
  pg.stroke(features.cornshadowab);
  pg.strokeWeight(g[1]);  
  pg.line(x+g[4],y,x+g[8],y-myRandom(g[8],g[16]));  
  pg.line(x+g[4],y-g[10],x+g[8],y-myRandom(g[18],g[30]));  
  pg.line(x+g[12],y,x+g[16],y-myRandom(g[8],g[16]));
  pg.line(x+g[12],y-g[10],x+g[16],y-myRandom(g[18],g[30]));
  pg.noStroke();
}
function pgfraybottom(i, j) {
  let x = i;
  let y = j;
  pg.noStroke();
  pg.fill(features.cornshadow);
  pg.beginShape();
  pg.vertex(x + g[6], y);
  pg.curveVertex(x + g[4], y);
  pg.curveVertex(x + myRandom(g[3], g[7]), y + myRandom(g[10], g[20]));
  pg.curveVertex(x + myRandom(g[3], g[7]), y + myRandom(g[25], g[35]));
  pg.vertex(x + myRandom(g[0], g[10]), y + myRandom(g[30], g[45]));
  pg.curveVertex(x + myRandom(g[7], g[11]), y + myRandom(g[25], g[35]));
  pg.curveVertex(x + myRandom(g[7], g[11]), y + myRandom(g[10], g[20]));
  pg.vertex(x + g[10], y);
  pg.endShape(CLOSE);
  pg.beginShape();
  pg.vertex(x + g[14], y);
  pg.curveVertex(x + g[14], y);
  pg.curveVertex(x + myRandom(g[11], g[15]), y + myRandom(g[10], g[20]));
  pg.curveVertex(x + myRandom(g[11], g[15]), y + myRandom(g[25], g[35]));
  pg.vertex(x + myRandom(g[8], g[18]), y + myRandom(g[30], g[45]));
  pg.curveVertex(x + myRandom(g[15], g[19]), y + myRandom(g[25], g[35]));
  pg.curveVertex(x + myRandom(g[15], g[19]), y + myRandom(g[10], g[20]));
  pg.vertex(x + g[18], y);
  pg.endShape(CLOSE);
  pg.fill(features.f1h);
  pg.beginShape();
  pg.vertex(x + g[4], y);
  pg.curveVertex(x + g[4], y);
  pg.curveVertex(x + myRandom(g[3], g[5]), y + myRandom(g[10], g[15]));
  pg.curveVertex(x + myRandom(g[3], g[5]), y + myRandom(g[25], g[30]));
  pg.vertex(x + myRandom(g[0], g[8]), y + myRandom(g[30], g[40]));
  pg.curveVertex(x + myRandom(g[7], g[9]), y + myRandom(g[25], g[30]));
  pg.curveVertex(x + myRandom(g[7], g[9]), y + myRandom(g[10], g[15]));
  pg.vertex(x + g[8], y);
  pg.endShape(CLOSE);
  pg.beginShape();
  pg.vertex(x + g[12], y);
  pg.curveVertex(x + g[12], y);
  pg.curveVertex(x + myRandom(g[11], g[13]), y + myRandom(g[10], g[15]));
  pg.curveVertex(x + myRandom(g[11], g[13]), y + myRandom(g[25], g[30]));
  pg.vertex(x + myRandom(g[8], g[16]), y + myRandom(g[30], g[40]));
  pg.curveVertex(x + myRandom(g[15], g[17]), y + myRandom(g[25], g[30]));
  pg.curveVertex(x + myRandom(g[15], g[17]), y + myRandom(g[10], g[15]));
  pg.vertex(x + g[16], y);
  pg.endShape(CLOSE);
  pg.stroke(features.cornshadowab);
  pg.strokeWeight(g[1]);  
  pg.line(x+g[4],y,x+g[8],y+myRandom(g[8],g[16]));  
  pg.line(x+g[4],y+g[10],x+g[8],y+myRandom(g[18],g[30]));  
  pg.line(x+g[12],y,x+g[16],y+myRandom(g[8],g[16]));
  pg.line(x+g[12],y+g[10],x+g[16],y+myRandom(g[18],g[30]));
  pg.noStroke();
}

